---
title: "Aufgabe 1"
subtitle: "Abfluss der Donau bei Hofkirchen"
author: "Matthias Baitsch"
output: html_document
---

# 1. Einlesen und Aufbereiten der Daten *To-DO: angemessene Formulierung*

Lesen Sie die Datei aus `"daten/6342800.day` ein und bereiten Sie die Daten sinnvoll auf.

# 2. Plots der Abflüsse

Stellen Sie einen Streuplot der Abflüsse dar. Erstellen Sie separat für jedes Jahr einen Boxplot der Abflüsse.

# 3. Linearer Trend

Berechnen Sie die Ausgleichsgerade und geben Sie den Anstieg des Abflusses in den letzten 100 Jahren an.

# 4. Statistische Kennwerte

Bestimmen Sie die üblichen statistischen Kennwerte für den Abfluss.

# 5. Standardabweichung für jedes Jahr

Stellen sie die Standardabweichung des Abflusses für jedes Jahr in einer Tabelle dar.

# 6. Standardabweichung über die Jahre

Stellen sie die Standardabweichung des Abflusses grafisch in einem Plot dar. Bewerten Sie ,ob ein linearer Trend zu erkennen ist.

# 7. Jahre mit kleinster/größter Standardabweichung

Bestimmen Sie die drei Jahre mit der jeweils kleinsten und jeweils größten Standardabweichung. Stellen Sie für diese Jahre den Abfluss über das komplette Jahr grafisch dar.

# 8. Weitere Jahre mit besonderem Ereignis

Bestimmen Sie das Jahr mit dem jeweils kleinsten und jeweils größten Gesamtabfluss. Stellen Sie für diese Jahre den Abfluss über das komplette Jahr grafisch dar.

# 9. Monats-Mittelwerte

Stellen Sie die Mittelwerte sowie das obere und untere Quartil jedes Monats dar. Bewerten Sie kurz das Ergebnis.

# 10. Verteilung

Stellen Sie die Verteilung des Abflusses sowohl als Histogramm als auch als empirische Verteilungsfunktion dar.

# 11. Normalverteilung

Überprüfen Sie grafisch, ob eine Normalverteilung vorliegt.

# 12. QQ-Plot

Stellen Sie den Abfluss in einem QQ-Plot dar und bewerten Sie das Ergebnis.